---
title: "lab4"
author: "Nathanael Reese"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    theme: darkly
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1

```{r}
getwd()
```

# Task 2

```{r}
spruce=read.csv("SPRUCE.csv")
tail(spruce)

```

# Task 3

```{r}
library(s20x)
trendscatter(Height~BHDiameter,f=0.5, data=spruce)
spruce.lm=with(spruce, lm(Height~BHDiameter))
height.res=residuals(spruce.lm)
height.fit=fitted(spruce.lm)
plot(height.res~height.fit)
trendscatter(height.res~height.fit) # Quadratic Function
plot(spruce.lm)
normcheck(spruce.lm, shapiro.wilk = TRUE)
# P-Value = 0.29
# The null hypothesis in this case is 0.5 when we set it in the trendscatter code snippet
# The data is not viable because of the presence of a quadratic formula when plotting the residuals.
```

# Task 4

```{r}
quad.lm = with(spruce, lm(Height~BHDiameter+I(BHDiameter^2)))
plot(quad.lm)
quad.res=residuals(quad.lm)
quad.fit=fitted(quad.lm)
plot(quad.lm)
normcheck(quad.lm, shapiro.wilk = T)
# P - Value = 0.684
# 0.684 > 0.5 so we are good!!!
```

# Task 5

```{r}
summary(quad.lm)
coef(quad.lm)
data = 15:24
predict20x(quad.lm,data.frame(BHDiameter = data, `I(BhDiameter)^2`=data^2))
predict(spruce.lm, data.frame(BHDiameter=c(15,18,20)))
anova(quad.lm, spruce.lm)
height.qfit=fitted(quad.lm)

RSS=with(spruce, sum((Height-height.qfit)^2))
RSS
MSS = with(spruce, sum((height.qfit-mean(Height))^2))
MSS

TSS = with(spruce, sum((Height-mean(Height))^2))
TSS
MSS/TSS

```

# Task 6

```{r}
cooks20x(quad.lm)
# Cook's distance or Cook's D is a commonly used estimate of the influence of a data point when performing a least-squares regression analysis.
quad2.lm=lm(Height~BHDiameter + I(BHDiameter^2) , data=spruce[-24,])
summary(quad2.lm)
summary(quad.lm)
layout(matrix(1:2,nc=2,byrow=TRUE))
cooks20x(quad.lm)
cooks20x(quad2.lm)
# The greatest cooks distance is now half of the previous so we are rocking and rolling!


```

# Task 7

```{r}
sp2.df=within(spruce, X<-(BHDiameter-20)*(BHDiameter>20)) # this makes a new variable and places it within the same df
sp2.df

lmp=lm(Height~BHDiameter + X,data=sp2.df)
tmp=summary(lmp)
names(tmp)
myf = function(x,coef){
  coef[1]+coef[2]*(x) + coef[3]*(x-18)*(x-18>0)
}
plot(spruce,main="Piecewise regression")
myf(0, coef=tmp$coefficients[,"Estimate"])
curve(myf(x,coef=tmp$coefficients[,"Estimate"] ),add=TRUE, lwd=2,col="Blue")
abline(v=18)
text(18,16,paste("R sq.=",round(tmp$r.squared,4) ))
```

# Task 8

```{r}
library(MATH4753REES)
myfun(10)
```

# EXTRA!!!

```{r}

```
